name: firstlvlpets
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  path_provider: ^2.1.2
  supabase_flutter: ^2.4.0
  image_picker: ^1.0.7
  flutter_image_compress: ^2.2.0
  introduction_screen: ^3.1.14
  infinite_scroll_pagination: ^4.0.0
  email_validator: ^2.1.17
  fancy_password_field: ^2.0.6
  provider: ^6.1.2
  video_player: ^2.8.5
  google_maps_flutter: ^2.2.8
  location: ^6.0.1
  sentry_flutter: ^7.19.0
  # flutter_polyline_points: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
