# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build_and_Test

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml # path to pubspec.yaml
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:" # optional, change this to force refresh cache

      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk


      - run: ls -a 
      - run: ls -a ./build
      - run: ls -a ./build/app
      - run: ls -a ./build/app/outputs
      # - run: flutter build apk # debug or release? is debug faster?
      # - run: flutter build appbundle

      # TODO: caching

      - uses: actions/upload-artifact@v4
        with:
          name: App Release
          path: ./build/app/outputs/flutter-apk/
          # path: ${{env.FLUTTER_ROOT}}/build/app/outputs/flutter-apk/app-release.apk