# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: iOS_Release

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
  push:
    branches: [ "no-branch" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml # path to pubspec.yaml
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:" # optional, change this to force refresh cache

      - run: flutter pub get
      - run: flutter test
      #- run: flutter build ios --release --no-codesign
      - run: flutter build ipa --release --no-codesign

      - uses: actions/upload-artifact@v4
        with:
          name: App Release
          #path: /Users/runner/work/flutter-test/flutter-test/build/ios/iphoneos/ # iOS Build
          #path: /Users/runner/work/flutter-test/flutter-test/build/ios/archive/Runner.xcarchive
          path: /Users/runner/work/flutter-test/flutter-test/build/ios/ipa


